"use client";

import React, { useState, useEffect } from "react";
import {
  FileText,
  ArrowLeft,
  Shield,
  User,
  AlertTriangle,
  Globe,
  Lock,
  Mail,
  ChevronRight,
  Sun,
  Moon,
} from "lucide-react";
import { motion } from "motion/react";
import { twMerge } from "tailwind-merge";
import { useTheme, usePalette } from "../../utils/ThemeContext";

const TERMS = [
  {
    id: "acceptance",
    icon: <FileText size={18} />,
    title: "1. Acceptance of Terms",
    color: "violet",
    content: [
      "By accessing or using Stylist BGMI (the Service), you agree to be bound by these Terms and Conditions. If you do not agree, please discontinue use immediately.",
      "We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the revised terms.",
      "These terms apply to all visitors, users, and others who access the Service.",
    ],
  },
  {
    id: "service",
    icon: <Globe size={18} />,
    title: "2. Description of Service",
    color: "blue",
    content: [
      "Stylist BGMI is a free, web-based tool that generates stylised name suggestions for use in the game Battlegrounds Mobile India (BGMI).",
      "The Service provides font transformations, symbol libraries, and name combination suggestions based on publicly available Unicode characters.",
      "The Service is provided as-is without any guarantees of availability, accuracy, or fitness for a particular purpose.",
      "We do not guarantee that any generated name will be accepted by BGMI. Game rules are subject to change by Krafton at any time.",
    ],
  },
  {
    id: "use",
    icon: <User size={18} />,
    title: "3. Acceptable Use",
    color: "emerald",
    content: [
      "You may use the Service for personal, non-commercial name generation purposes only.",
      "You must not use the Service to generate names that contain hate speech, slurs, threats, or discriminatory content.",
      "You must not attempt to scrape, clone, reverse-engineer, or republish the Service or its generated content for commercial purposes.",
      "You must not use automated bots or scripts to access the Service at a rate that disrupts normal operation.",
      "You agree to comply with all applicable laws and BGMI's own Terms of Service when using generated names.",
    ],
  },
  {
    id: "ip",
    icon: <Shield size={18} />,
    title: "4. Intellectual Property",
    color: "orange",
    content: [
      "BGMI, Battlegrounds Mobile India, and all related trademarks are the property of Krafton Inc. We are not affiliated with, endorsed by, or sponsored by Krafton.",
      "The design, code, and original content of this Service are owned by Stylist BGMI. All rights reserved.",
      "Unicode characters used in font transformations are part of the public Unicode standard and are not proprietary to this Service.",
      "You retain no intellectual property rights over generated name suggestions — they are transformations of your own input.",
    ],
  },
  {
    id: "disclaimer",
    icon: <AlertTriangle size={18} />,
    title: "5. Disclaimers & Limitation of Liability",
    color: "yellow",
    content: [
      "The Service is provided without warranties of any kind, express or implied, including but not limited to merchantability or fitness for a particular purpose.",
      "We are not liable for any account bans, name rejections, or penalties imposed by Krafton resulting from use of names generated by this Service.",
      "We are not responsible for any loss of data, Rename Cards, or in-game currency spent on names that are subsequently rejected.",
      "Our total liability for any claim arising from use of the Service is limited to zero, as this is a free service.",
    ],
  },
  {
    id: "privacy",
    icon: <Lock size={18} />,
    title: "6. Privacy",
    color: "pink",
    content: [
      "We do not collect, store, or share personal data. Names you type into the generator are processed entirely client-side in your browser.",
      "We do not use tracking cookies, advertising pixels, or third-party analytics that collect personally identifiable information.",
      "Standard server access logs (IP address, timestamp, requested URL) may be retained for up to 30 days for security purposes, then deleted.",
      "We do not sell, rent, or share any user data with third parties.",
    ],
  },
  {
    id: "contact",
    icon: <Mail size={18} />,
    title: "7. Contact",
    color: "cyan",
    content: [
      "For questions, concerns, or DMCA notices regarding these terms, please reach out via our community channels.",
      "We aim to respond to all legitimate queries within 5 business days.",
      "For bug reports or feature requests, please use the feedback option within the app.",
    ],
  },
];

const COLOR_ACCENTS = {
  violet: {
    bg: "rgba(124,58,237,0.1)",
    border: "rgba(124,58,237,0.25)",
    text: "#8b5cf6",
    dot: "#7c3aed",
  },
  blue: {
    bg: "rgba(59,130,246,0.1)",
    border: "rgba(59,130,246,0.25)",
    text: "#60a5fa",
    dot: "#3b82f6",
  },
  emerald: {
    bg: "rgba(16,185,129,0.1)",
    border: "rgba(16,185,129,0.25)",
    text: "#34d399",
    dot: "#10b981",
  },
  orange: {
    bg: "rgba(249,115,22,0.1)",
    border: "rgba(249,115,22,0.25)",
    text: "#fb923c",
    dot: "#f97316",
  },
  yellow: {
    bg: "rgba(234,179,8,0.1)",
    border: "rgba(234,179,8,0.25)",
    text: "#fbbf24",
    dot: "#eab308",
  },
  pink: {
    bg: "rgba(236,72,153,0.1)",
    border: "rgba(236,72,153,0.25)",
    text: "#f472b6",
    dot: "#ec4899",
  },
  cyan: {
    bg: "rgba(6,182,212,0.1)",
    border: "rgba(6,182,212,0.25)",
    text: "#22d3ee",
    dot: "#06b6d4",
  },
};

function ThemeToggle({ p }) {
  const { dark, toggleTheme } = useTheme();
  return (
    <button
      onClick={toggleTheme}
      className="flex items-center gap-1.5 rounded-full px-3 py-1.5 border transition-all duration-300 hover:scale-105"
      style={{ background: p.bgTag, borderColor: p.border, color: p.textMuted }}
    >
      <motion.div
        key={dark ? "moon" : "sun"}
        initial={{ rotate: -30, opacity: 0 }}
        animate={{ rotate: 0, opacity: 1 }}
        transition={{ duration: 0.25 }}
      >
        {dark ? <Moon size={14} /> : <Sun size={14} />}
      </motion.div>
      <span className="text-[10px] font-bold uppercase tracking-wider hidden sm:inline">
        {dark ? "Dark" : "Light"}
      </span>
    </button>
  );
}

export default function TermsPage() {
  const p = usePalette();
  const [activeSection, setActiveSection] = useState("acceptance");

  useEffect(() => {
    document.title =
      "Terms & Conditions – BGMI Name Stylist | Privacy Policy & Usage Rules";
    const desc = document.querySelector('meta[name="description"]');
    if (desc)
      desc.setAttribute(
        "content",
        "Terms and Conditions for BGMI Name Stylist. Read our privacy policy, acceptable use policy, disclaimer, and intellectual property notice before using our free BGMI fancy name generator.",
      );
    const ogTitle = document.querySelector('meta[property="og:title"]');
    if (ogTitle)
      ogTitle.setAttribute("content", "Terms & Conditions – BGMI Name Stylist");
    const canon = document.querySelector('link[rel="canonical"]');
    if (canon && typeof window !== "undefined")
      canon.setAttribute("href", `${window.location.origin}/terms`);
  }, []);

  return (
    <div
      className="min-h-screen font-inter transition-colors duration-300"
      style={{ background: p.bg, color: p.text }}
    >
      {/* NAVBAR */}
      <nav
        className="w-full sticky top-0 z-50 border-b transition-colors duration-300"
        style={{
          background: p.bgNav,
          borderColor: p.border,
          backdropFilter: "blur(20px)",
          WebkitBackdropFilter: "blur(20px)",
        }}
      >
        <div className="w-full px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <a
              href="/"
              className="flex items-center gap-1.5 text-sm font-medium hover:text-violet-500 transition-colors"
              style={{ color: p.textMuted }}
            >
              <ArrowLeft size={15} /> Back
            </a>
            <div className="h-4 w-px" style={{ background: p.border }} />
            <div className="flex items-center gap-2">
              <div
                className="w-7 h-7 rounded-lg flex items-center justify-center font-black italic text-[11px] text-white"
                style={{
                  background: "linear-gradient(135deg,#7c3aed,#4f46e5)",
                }}
              >
                ID
              </div>
              <span className="font-bold text-sm" style={{ color: p.text }}>
                Stylist <span style={{ color: "#8b5cf6" }}>BGMI</span>
              </span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="hidden md:flex items-center gap-5">
              <a
                href="/"
                className="text-sm font-medium hover:text-violet-500 transition-colors"
                style={{ color: p.textMuted }}
              >
                Generator
              </a>
              <a
                href="/guidelines"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm font-medium hover:text-violet-500 transition-colors"
                style={{ color: p.textMuted }}
              >
                Guidelines
              </a>
              <a
                href="/terms"
                className="text-sm font-bold"
                style={{ color: "#8b5cf6" }}
              >
                Terms
              </a>
            </div>
            <ThemeToggle p={p} />
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-14">
        {/* Hero */}
        <div className="mb-14">
          <div
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border text-xs font-semibold mb-5"
            style={{
              background: "rgba(124,58,237,0.1)",
              borderColor: "rgba(124,58,237,0.25)",
              color: "#8b5cf6",
            }}
          >
            <FileText size={12} /> Legal Document
          </div>
          <h1
            className="text-4xl md:text-5xl font-black tracking-tight mb-4"
            style={{ color: p.text }}
          >
            Terms &{" "}
            <span
              className="bg-clip-text text-transparent"
              style={{
                backgroundImage: "linear-gradient(135deg,#a78bfa,#60a5fa)",
              }}
            >
              Conditions
            </span>
          </h1>
          <p
            className="text-lg max-w-2xl leading-relaxed"
            style={{ color: p.textMuted }}
          >
            Please read these terms carefully before using Stylist BGMI. By
            using our service you agree to the following conditions.
          </p>
          <div className="flex flex-wrap gap-3 mt-6">
            {[
              "Effective: 1 January 2026",
              "Last updated: May 2026",
              "Jurisdiction: India",
            ].map((tag) => (
              <span
                key={tag}
                className="text-xs font-medium px-3 py-1 rounded-full border"
                style={{
                  color: p.tagText,
                  background: p.bgTag,
                  borderColor: p.tagBorder,
                }}
              >
                {tag}
              </span>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          {/* Sidebar */}
          <div className="md:col-span-1">
            <div
              className="sticky top-24 rounded-2xl border p-4 space-y-1 transition-colors duration-300"
              style={{ background: p.bgSidebar, borderColor: p.border }}
            >
              <p
                className="text-[10px] font-bold uppercase tracking-widest px-2 mb-3"
                style={{ color: p.tagText }}
              >
                Contents
              </p>
              {TERMS.map((t) => {
                const acc = COLOR_ACCENTS[t.color];
                const isActive = activeSection === t.id;
                return (
                  <button
                    key={t.id}
                    onClick={() => {
                      setActiveSection(t.id);
                      document.getElementById(t.id)?.scrollIntoView({
                        behavior: "smooth",
                        block: "start",
                      });
                    }}
                    className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-left text-sm transition-all duration-200"
                    style={{
                      background: isActive ? p.sidebarBtn : "transparent",
                      color: isActive ? acc.text : p.textMuted,
                      fontWeight: isActive ? 600 : 400,
                    }}
                  >
                    <span
                      className="w-1.5 h-1.5 rounded-full shrink-0"
                      style={{ background: isActive ? acc.dot : p.border }}
                    />
                    <span className="truncate">
                      {t.title.replace(/^\d+\.\s/, "")}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Content */}
          <div className="md:col-span-3 space-y-5">
            {TERMS.map((section, si) => {
              const acc = COLOR_ACCENTS[section.color];
              return (
                <motion.div
                  id={section.id}
                  key={section.id}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ delay: si * 0.04 }}
                  viewport={{ once: true }}
                  onViewportEnter={() => setActiveSection(section.id)}
                  className="rounded-2xl border p-7 transition-all duration-300 hover:border-violet-500/30"
                  style={{ background: p.bgCard, borderColor: p.border }}
                >
                  <div className="flex items-center gap-3 mb-5">
                    <div
                      className="p-2 rounded-lg border"
                      style={{
                        background: acc.bg,
                        borderColor: acc.border,
                        color: acc.text,
                      }}
                    >
                      {section.icon}
                    </div>
                    <h2
                      className="text-lg font-bold"
                      style={{ color: acc.text }}
                    >
                      {section.title}
                    </h2>
                  </div>
                  <div className="space-y-3">
                    {section.content.map((para, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <div
                          className="w-1.5 h-1.5 rounded-full mt-2 shrink-0"
                          style={{ background: acc.dot }}
                        />
                        <p
                          className="text-sm leading-relaxed"
                          style={{ color: p.textSub }}
                        >
                          {para}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}

            {/* Agreement */}
            <div
              className="rounded-2xl border p-7"
              style={{
                background: "rgba(124,58,237,0.05)",
                borderColor: "rgba(124,58,237,0.25)",
              }}
            >
              <div className="flex items-start gap-4">
                <div
                  className="p-2 rounded-lg border shrink-0"
                  style={{
                    background: "rgba(124,58,237,0.1)",
                    borderColor: "rgba(124,58,237,0.25)",
                  }}
                >
                  <Shield size={20} style={{ color: "#8b5cf6" }} />
                </div>
                <div>
                  <h3
                    className="text-base font-bold mb-2"
                    style={{ color: "#8b5cf6" }}
                  >
                    Your Agreement
                  </h3>
                  <p
                    className="text-sm leading-relaxed mb-4"
                    style={{ color: p.textMuted }}
                  >
                    By continuing to use Stylist BGMI you confirm you have read,
                    understood, and agree to these Terms and Conditions in full.
                    If you are under 13 years of age, please have a parent or
                    guardian review these terms with you.
                  </p>
                  <a
                    href="/"
                    className="inline-flex items-center gap-1.5 text-sm font-semibold hover:opacity-75 transition-opacity"
                    style={{ color: "#8b5cf6" }}
                  >
                    Return to Generator <ChevronRight size={14} />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* FOOTER */}
      <footer
        className="border-t w-full mt-16 transition-colors duration-300"
        style={{ background: p.bgFooter, borderColor: p.border }}
      >
        <div className="w-full px-6 py-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-xs" style={{ color: p.tagText }}>
            © 2026 Stylist BGMI. Not affiliated with Krafton Inc.
          </p>
          <div className="flex gap-6">
            <a
              href="/"
              className="text-xs hover:text-violet-500 transition-colors"
              style={{ color: p.textMuted }}
            >
              Generator
            </a>
            <a
              href="/guidelines"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs hover:text-violet-500 transition-colors"
              style={{ color: p.textMuted }}
            >
              Guidelines
            </a>
            <a
              href="/terms"
              className="text-xs font-bold"
              style={{ color: "#8b5cf6" }}
            >
              Terms
            </a>
          </div>
        </div>
      </footer>

      <style jsx global>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');
        .font-inter { font-family: 'Inter', sans-serif; }
        ::-webkit-scrollbar { width: 5px; } ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(124,58,237,0.3); border-radius: 99px; }
      `}</style>
    </div>
  );
}
